// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRDCS.Data;

#nullable disable

namespace SRDCS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117112041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole<int>");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SACCO_Manager",
                            NormalizedName = "SACCO_MANAGER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accounts_Officer",
                            NormalizedName = "ACCOUNTS_OFFICER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Data_Entry_Officer",
                            NormalizedName = "DATA_ENTRY_OFFICER"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Analyst",
                            NormalizedName = "ANALYST"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = 6,
                            Name = "System_Admin",
                            NormalizedName = "SYSTEM_ADMIN"
                        });
                });

            modelBuilder.Entity("SRDCS.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<int>("ReturnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ReturnId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.FinancialData", b =>
                {
                    b.Property<int>("FinancialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialId"));

                    b.Property<int>("ExitedMembers")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestEarnedMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansIssuedMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansRepaidMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MemberDeposits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NewMembers")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLoanees")
                        .HasColumnType("int");

                    b.Property<decimal>("OutstandingLoanBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PAR30")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PAR60")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PAR90")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ReturnId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShareCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAssets")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpensesMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomeMonthly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilities")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLoansCumulative")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("int");

                    b.HasKey("FinancialId");

                    b.HasIndex("ReturnId")
                        .IsUnique();

                    b.ToTable("FinancialData");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.MonthlyReturn", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<DateTime>("ReportingMonth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<int>("SACCOId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int");

                    b.HasKey("ReturnId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("SACCOId", "ReportingMonth")
                        .IsUnique();

                    b.ToTable("MonthlyReturns");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.SACCO", b =>
                {
                    b.Property<int>("SACCOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SACCOId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SACCOName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SACCOType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SACCOId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasFilter("[RegistrationNumber] IS NOT NULL");

                    b.ToTable("SACCOs");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SACCOId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("SACCOId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("SRDCS.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.Document", b =>
                {
                    b.HasOne("SRDCS.Models.Entities.MonthlyReturn", "MonthlyReturn")
                        .WithMany("Documents")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRDCS.Models.Entities.User", "UploadedByUser")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyReturn");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.FinancialData", b =>
                {
                    b.HasOne("SRDCS.Models.Entities.MonthlyReturn", "MonthlyReturn")
                        .WithOne("FinancialData")
                        .HasForeignKey("SRDCS.Models.Entities.FinancialData", "ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyReturn");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.MonthlyReturn", b =>
                {
                    b.HasOne("SRDCS.Models.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy");

                    b.HasOne("SRDCS.Models.Entities.SACCO", "SACCO")
                        .WithMany("MonthlyReturns")
                        .HasForeignKey("SACCOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRDCS.Models.Entities.User", "SubmittedByUser")
                        .WithMany("MonthlyReturns")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SACCO");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.User", b =>
                {
                    b.HasOne("SRDCS.Models.Entities.SACCO", "SACCO")
                        .WithMany("Users")
                        .HasForeignKey("SACCOId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SACCO");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.MonthlyReturn", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("FinancialData")
                        .IsRequired();
                });

            modelBuilder.Entity("SRDCS.Models.Entities.SACCO", b =>
                {
                    b.Navigation("MonthlyReturns");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SRDCS.Models.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Documents");

                    b.Navigation("MonthlyReturns");
                });
#pragma warning restore 612, 618
        }
    }
}
